### PR TITLE
Native Docker support

### PR DESCRIPTION
**Pull request by trivoallan**
Hello,

This PR adds native Docker support for the Directus API project.

It covers needs that are not adressed by the [directus/docker](https://github.com/directus/docker) project :

- **Compatibility with Docker oriented CI/CD solutions** : [Docker Cloud](https://cloud.docker.com), [Gitlab
CI](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html), [Jenkins](https://jenkins.io/doc/book/pipeline/docker/), etc.
- **Better operability of the Docker image** : it is based on the official PHP Docker images and does not add NGINX on top of PHP-FPM
- **Explicit expression of application dependencies modifications** : application code requiring an update of the depencies will be commited together with the modified Dockerfile describing the new dependencies. This should enhance and facilitate application testing
- **Fast and easy development environment setup**  : the `docker-compose up` command fires up a host-accessible Directus API in seconds, along with a dedicated database and a database management application

Documentation currently resides in the [DOCKER.md](DOCKER.md) file but I would be happy to turn it into a PR if someone can point me to the appropriate Git repository :)

Example Directus API CI pipelines based on this PR are available on the following platforms :  [Docker Cloud](https://cloud.docker.com/u/constructionsincongrues/repository/docker/constructionsincongrues/directus-api/), [Semaphore CI](https://semaphoreci.com/constructions-incongrues/directus-api)

I'll provide similar PR for the other Directus components should this PR be approved.

Thanks in advance for your comments.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
That's quite the setup @trivoallan. Have you seen the docker repository? https://github.com/directus/docker/

Can we move this PR there instead? 

@wolfulus ping

**Comment by WoLfulus** [comment]
I see this is more related to a "development environment" with docker right? I see there's no changes related to how api loads configurations and stuff.

There are a lot of issues we raised over several months related to docker that we are trying to solve in #930 and docker's refactor branch right now.

**Comment by trivoallan** [comment]
Hi,

@rijkvanzanten @WoLfulus this PR is about both issues :

- @WoLfulus : you are right : there are absolutely no changes to Directus API. It implements an fast and easy to setup (yet powerful) Docker Compose based development environment 100% compatible with how Directus works at the moment. It is not related to #930. Support for configuration based on environment variables is important but not here.
- @rijkvanzanten : that's actually my point : i think having a separate docker repository is not good design. It's like setting up separate repositories for Makefiles or composer.json

This PR adds another good thing : the Dockerfile produces an images better suited for deploying in a cloud environment.

**Comment by rijkvanzanten** [comment]
> i think having a separate docker repository is not good design

I think that's up for discussion honestly. In my opinion, Docker is _another_ way (vs _the_ way) of deploying the API. It's the same reason the Caddyfile or the Nginx config files aren't in the main repo.

**Comment by trivoallan** [comment]
> It's the same reason the Caddyfile or the Nginx config files aren't in the main repo.

Docker is not comparable to Caddy and NGINX. The former are web servers while Docker is a build tool, a execution environment and packaging solution.

Build tool configuration files are usually part of an application codebase.

**Comment by WoLfulus** [comment]
> i think having a separate docker repository is not good design

I agree with that too, but there were many factors that made us separate the whole thing somewhere else (dependencies between projects, people raising so many issues for something that we weren't maintaining, team knowledge/familiaritywith the technology, etc...):

The new Dockerfiles will enable us to:

- Have a single base image for each project/variant (api-apache, api-nginx, api-caddy) which is easier to maintain and fix bugs
- Extend the base image with custom packages and extensions (php, interface, composer...)
- Have an extremely simple Dockerfile (with ONBUILD steps) in it's own repository (just like you did, but without maintaining the whole Dockerfile stuff here)

I'm trying to get the best of all worlds, but right now there are some minor issues we must care about in order to provide a better Docker support (not only inside their own repositories).

We can always rethink the approach later, but for now IMHO we should solve what is pending first.

**Comment by trivoallan** [comment]
Another argument in favor : most (if not all) CI / CD tools look for a Dockerfile in the application repository.

I don't know of any of those tool that makes it possible to use Docker containers within the pipeline if the Dockerfile is located outside the application Git repository.

References from proeminent CI / CD tools' documentation : 

- https://jenkins.io/doc/book/pipeline/docker/#dockerfile
- https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
- https://docs.travis-ci.com/user/docker/
- https://circleci.com/docs/2.0/building-docker-images/

**Comment by trivoallan** [comment]
> * Have a single base image for each project/variant (api-apache, api-nginx, api-caddy) which is easier to maintain and fix bugs

This is not PHP / Docker best practices : the best way (for now) to operate a PHP application in a containerized context is to have two separate container : one with the PHP sources exposed via a PHP-FPM interface and the other with a web server for exposing static resources and PHP-FPM responses. 

This has obvious advantages in maintenance, coupling, etc. It also makes it possible to people running the application to use whatever web server serves their needs.

> * Extend the base image with custom packages and extensions (php, interface, composer...)
> * Have an extremely simple Dockerfile (with ONBUILD steps) in it's own repository (just like you did, but without maintaining the whole Dockerfile stuff here)

I was planning to refactor using ONBUILD instructions once i better know the common ground between execution environments of the different Directus components :)

You are talking about "new Dockerfiles" and a "Docker refactoring branch". Could you point me to those maybe i could help.

**Comment by WoLfulus** [comment]
https://github.com/directus/docker/tree/refactor/full and #930

**Comment by dev7ch** [comment]
Actually i like the idea of a very simple docker spin up, especially for local development.

What i would like to mention is the introduction of the `.env` file, this should not be in a repository and leads into conflicts in security. Why not rename it to `.env.dist` and put `.env` in .gitignore ?

**Comment by trivoallan** [comment]
@dev7ch you are right, i just renamed the file

**Comment by dev7ch** [comment]
What is about this? 

Is this considered to add into the master branch to please Developers and DevOps to bring Directus a bit closer to the  more less most widely adapted  dev habbits of today?

**Comment by WoLfulus** [comment]
Hi guys!

As I mentioned in #1022, we're about to merge some code that will help us with docker, and to avoid reimplementing docker stuff on api/app project we'll keep it under `directus/docker`. We're also working on bringing a dev environment into api project too, but using directus/docker images instead.

@bjgajjar we can close this one too

**Pull request closed without merging**
