### PR TITLE
[WIP] Feat/replicator

### PR DESCRIPTION
**Pull request by cesasol**
This is my current work for [#712](https://github.com/directus/app/issues/712) any feedback welcome

### CODE REVIEW

**Comment by benhaynes** [comment]
Whoa, awesome! Can't wait to check this out, thanks @cesasol !

**Comment by rijkvanzanten** [comment]
This is cool @cesasol!

Couple of points so far:
* It won't save because the API expects a JSON object (we should be able to strip the JSON.stringify to make it work.
* It would be super if this interface would render other interfaces, instead of using "custom" `v-input`s for the field. That way you could repeat an inline calendar or map or any other interface as well 😄

**Comment by benhaynes** [comment]
Hey @cesasol — I haven't seen this yet, but I wanted to pass along the latest design I've come up with for this interface. I've simplified it as much as possible for this MVP:

Screen Shot 2019-03-25 at 12 39 13 PM

**Comment by Log1x** [comment]
All of this looks great so far. Definitely a +1 on rendering other interfaces. Having something simple like a calendar for date fields is a must.

Once this is polished and implemented, this will be a massive leap in the right direction for making Directus viable for an incredible amount of use-cases that I and I know MANY others need, especially for agency-related work.

**Comment by bjgajjar** [comment]
Hey @cesasol 

**Extensions** are moved to the `APP` repo. So kindly send this PR to `APP` repo.

**Pull request closed without merging**
