### PR TITLE
add gitpod.io support

### PR DESCRIPTION
**Pull request by PostPollux**
I finally managed to add gitpod.io support for the api aswell.

Now we can spin up a fully functional develop environment for the api with just one click!
Try it yourself:  http://gitpod.io#https://github.com/PostPollux/api/tree/gitpod_support

It downloads all the dependencies, adds the api.php (copy of api_sample.php), downloads the demo.sql, creates the database, imports the demo.sql, deletes that demo.sql afterwards to keep things clean and finally starts the apache server.

It also nicely prints the url where you can reach your api and other help to keep things straight forward and easy.

The nice thing: If you stop your workspace and later start that one again (not spinning up a new one), all the dependencies and your sql data is already there, so it starts up really fast.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I have never heard of or used gitpod.io, so I'm not entirely sure what I'm looking at or how to review it 🤷‍♂ 

Is it just the online IDE? Can you use it to spin up the API somewhere else? If it's just for development purposes, how does this compare to using Docker locally?

**Comment by PostPollux** [comment]
Gitpod is only for development purpose. It's defineteley not ment for deployment.

It's basically a One-Click Online IDE for GitHub that launches ready-to-code development environments where all dependencies are already installed and everything is already correctly setup.

A gitpod workspace is started by prefixing any GitHub URL with "gitpod.io/#". It also automatically starts it in the right branch if you have selected one. If you don't have any configuration files in the repository it still spins up, but it's not ready to code because the dependencies are not installed etc...
So that's what the .gitpod.yml is doing. It basically lists what commands to execute 

If you have a look at the code it's not very difficult to maintain:

```
tasks:
  - init: >
      composer install &&
      cp config/api_sample.php config/api.php &&
      echo "downloading demo database..." &&
      curl https://directus.github.io/demo-sql/demo.sql > demo.sql &&
      echo "please wait while demo database (demo.sql) is being imported..." &&
      mysql -u root < gitpod-helper.sql &&
      mysql -u root -p'root' directus < demo.sql &&
      rm demo.sql

    command: >
      apachectl start &&
      ...
```
`init `will be executed if a workspace is freshly spinned up. If you stop it and restart the same workspace later on it will not be executed again. `command` will always be executed.

So it's just:
1. `composer install` install the dependencies
2. `cp config/api_sample.php config/api.php` make sure we have an api.php
3. `curl https://directus.github.io/demo-sql/demo.sql > demo.sql` download the demo.sql
4. `mysql -u root < gitpod-helper.sql` execute that sql helper script that creates the "directus" database and makes sure that the the "root" user also has "root" as password to match the config api.php
5. `mysql -u root -p'root' directus < demo.sql` import the demo.sql
6. `rm demo.sql` delete the demo.sql so we don't end up having an uncommited file in the repository


The benefits:
- It lowers the barrier to just play with the code and try to make some changes. I think we all have been there. You are interested in a project and would like to try to make a quick fix, but you first have to manage to get a full working development environment on your computer. That takes time. First you have to read through the docs and follow the instructions. Sometimes they are not 100% clear and you end up getting errors and trying to get rid of them to finally get it to a point where you can start to code on the project.
- If you are on a computer where you haven't already setup the develompment environment and you maybe are even not supposed to install any software you still can work on it with just a click, because you install nothing.


I can try to add a section on the docs to shortly explain what it is about and how to work with it. Like mentioning that it is only for development purpose. 

And showing a basic workflow like:

If you just want to play and try it out: just use this link

If you are serious of making a pullrequest and want to use gitpod: 
1. Fork the repository
2. make a branch for your feature/fix and select that branch in github (so it is visible in the url)
2. startup a gitpod workspace from your repository by prefixing the url with "gitpod.io#"
3. Make your changes. Commit them and push them to your repository
4. Make a pull request.


btw: 
Is it correct that we have to submit all the pull requests to the `master` branch and not to the `development` branch? 
Because at the moment under "contributing" in the README.md files it says:
"Submit all pull-requests to the master branch of our api and app repositories."

**Comment by benhaynes** [comment]
My only concern is that GitPod is a paid service. I know they have an open-source plan that gives you 100 hours for free, but it's still a proprietary platform that requires an account, and it seems odd to include it so prominently in our software. That said, I haven't tried GitPod, so maybe it's more amazing than I'm giving it credit for... like Docker.

@WoLfulus @bjgajjar @hemratna — do any of you have experience with GitPod? Thoughts?

**Comment by PostPollux** [comment]
@benhaynes 
Yes it's a proprietary platform. That's true. But github itself is proprietary, too. Nobody is forced to use gitpod. You can still set up your dev environment like before. It's just a shortcut for newcomers or people that are not so fond of constantly setting up new dev environments manually. 

You don't really have to create an extra account. It is used with your github account, so the only thing you have to do is grant a permission when you start it the first time.

I think 100 hours a month are more than enough. If you are going to invest more than 100 hours a month to a project you probably are so serious about it, that you prefer to have a local dev environment anyways.

I actually found out about gitpod.io by chance two weeks ago and for me it was like: "This is awesome! With this i can start hacking on a project in minutes without all that tedious setup!"
Well, that's how I like to work. I love to quickly start hacking on a project. I'm interested in solving a particular issue, not in setting up a dev environment to hopefully come to a point where I can fix the actual issue. There were several times where I ended up not trying to fix something in a project at all, because I hadn't had the time or I jsut didn't feel like setting up another development environment.

Well, but it's up to you if you want to include it. I thought it might help to get new contributers on board easily. But maybe I'm wrong. As I said, I learned about gitpod only two weeks ago. So it's possible that it doesn't make a lot of sense for directus and I didn't see it because I was hyped, as I liked it so much.

**Comment by WoLfulus** [comment]
This is cool and stuff, but I _personally_ wouldn't merge this since it can launched externally (you just don't get the automated setup). But this is not my call, and I'll leave it to @rijkvanzanten and @bjgajjar to decide.

**Comment by PostPollux** [comment]
@WoLfulus  of course you can launch it externally with gitpod. But if there is no .gitpod.yml present in the repository it doesn't make a lot of sense. Because then you are again at the point where you have to setup your dev environment manually...

**Comment by hemratna** [comment]
@benhaynes It's looking good to me.
Actually I never worked with gitpod personally, But in the past, I used to work with [codeanywhere](https://codeanywhere.com/) which is simply an online code editor.

As I understand from @PostPollux, To support gitpod we have to add one .yml file. 
So let's give it a try and see how the contributor benefits from it.

**Comment by benhaynes** [comment]
Thanks Hem — that makes sense to me, and I agree! Let's merge this in and give it some time to gauge the response from our community. If they find it useful we can keep it, if no one seems to want/use it we can always remove it later.

**Pull request merged**
