### PR TITLE
Allowing string relations

### LINKED ISSUE #798: Relations with string as primary key doesn't work
# Bug Report
Relationships doesn't work when using string based relation for example a slug relation or in the future with UUID

## Steps to Reproduce

1- Create a collection with a varchar primary key 
2- Create another collection and set a one to many or many to many relationship to the first collection
3- It will sabe to the database but will not follow relations with things like fields=*.* 

## Expected Behavior

Work the same way that it does with integer relations

## Actual Behavior

Doesn't resolver relations between collections

## Other Context & Screenshots

The record
image
The record with fields=*/*
image

## Technical Details

- Device: Any
- OS: Ubuntu (server and client)
- Web Server: Nginx 1.10.3
- PHP Version: 7.2
- Database: MySQL 5.7
- Install Method: The cloned full package at v7.0.18

### PR DESCRIPTION
**Pull request by cesasol**
This fixes #798 and paves the way for Matrix relationships

### CODE REVIEW

**Comment by benhaynes** [comment]
Thanks @cesasol — this seems like a super simple fix... but we just need to make sure it doesn't cause any adverse effects for the INT keys. We'll check it out asap! 👍

**Comment by kateerogers** [comment]
Is this going to be merged in any time soon?

**Comment by benhaynes** [comment]
It seems like a trivial change, but we need to make absolutely sure it doesn't break anything else. As of now, our Unit Tests are incomplete, so we can't rely on them — and need to check this manually. No ETA, but we'll get to it as soon as possible.

@theharshin — any other thoughts?

**Comment by theharshin** [comment]
@cesasol Thanks for PR 🙂 It is indeed a small change but will have a larger impact on how every relational fields work. I'm not sure if typecasting is really required if we're going to support `INT` & `STRING` both. @bjgajjar will have a look at this soon and will do manual testing for this.

**Comment by bjgajjar** [comment]
Thanks for the help @kateerogers

**Pull request merged**
