### PR TITLE
Fix O2M, M2O, and M2M relations in GraphQL queries

### PR DESCRIPTION
**Pull request by Owlree**
Reimplemented O2M and M2O relations. Changed translations to be treated as O2M relations. Added a special case check for integers to see if they represent M2O relations, private keys, or plain integers.

Tested O2M, M2O, and M2M. Tested M2M relations with two or more junction tables between the same two collections.

Fixes https://github.com/directus/api/issues/1412, https://github.com/directus/api/issues/1167, https://github.com/directus/api/issues/1394.

Does **NOT** fix https://github.com/directus/api/issues/1401.

### CODE REVIEW

**Comment by bjgajjar** [comment]
@Owlree  - Can you please resolve the merge conflicts here? So I can review the PR.

**Comment by bjgajjar** [comment]
@Owlree - Can you please verify that all these 13 files are modified in this PR? I am seeing only a single GraphQL file. So please resolve this conflict. So I can review it.

**Comment by dankostov** [comment]
Hi, has this been released?

**Comment by bjgajjar** [comment]
@dankostov - Nope. It's not even merged as there're some merge conflicts here. 

We're waiting for @Owlree  to resolve it.

**Comment by dankostov** [comment]
Hi @Owlree , are you going to have time to check this soon?

**Comment by EugenioSantos** [comment]
@Owlree  some expectation of correction forecast
 #1401 ?

**Pull request closed without merging**
