### PR TITLE
Remove scope from directus_settings

### LINKED ISSUE #594: Remove scope from directus_settings
# Bug Report

We don't use the `scope` column in directus_settings anymore. I'm not a 100% sure how the migrations have to be setup to get this done correctly.

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Adds a migration to remove the scope column.

Closes #594, ref https://github.com/directus/app/issues/1140

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@WellingGuzman mentioned on Slack that there are some places in the API code that relies on `scope` being there. Merging this now would cause issues as the code will be trying to access a column that doesn't exist

**Comment by rijkvanzanten** [comment]
@WellingGuzman Did you remove all other references to `scope` too?

**Comment by andreekeberg** [comment]
All references are definitely not removed as I just did a `git pull` and still an error that "**scope: This value should not be blank.**" when trying to set a "Color" in the Global Settings.

**Comment by rijkvanzanten** [comment]
@andreekeberg Have you ran the DB update with the `/update` endpoint or by using the button in settings?

**Comment by andreekeberg** [comment]
@rijkvanzanten Yes, I just found the button and tried this, and still got the same error.
I'm wondering if it could in some way be related to the bug that makes it impossible to select a logo, because of some kind of database migration. Both issues persist after the DB update.

**Comment by WellingGuzman** [comment]
Hey @andreekeberg, it seems to be an API error: `scope: This value should not be blank.`. Is the `directus_settings` table still have the `scope` column?

**Comment by andreekeberg** [comment]
Yes @WellingGuzman the `directus_settings` table still has this column after the DB update.

**Comment by WellingGuzman** [comment]
@andreekeberg Are you using the `master` branch of `directus/api` repository? This fix hasn't been released yet.

**Pull request merged**
