### PR TITLE
fix #1722

### LINKED ISSUE #1722: Error when updating WYSIWYG interface after upgrade to v8.5.0
I just updated via GIT from v8.4.0 to v8.5.0
On the app I go to `Settings` > `Collections & Fields` and select a current collection.
I click on an existing WYSIWYG interface and add fullscreen from the options.
On the front end I get an error:
> Trouble processing request. Try again after refreshing the page

On the console I get this error:
`Error: "Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(16777215) Null' at line 1)"
    a API.js:39
    request API.js:253
 error.js:6:22
    Ud error.js:6
    VueJS 2
    e fields.vue:448
    l runtime.js:45
    O runtime.js:271
    a runtime.js:97
    n asyncToGenerator.js:3
    m asyncToGenerator.js:29`

Changing `MySQL Datatype` from `MEDIUMTEXT` to `TEXT` at the same time as adding fullscreen option allows the updated setting to be saved.  

When I click back into the interface settings the `MySQL Datatype` reverts back to `MEDIUMTEXT`, but the fullscreen option is preserved offering a workaround.

### PR DESCRIPTION
**Pull request by dur41d**
set length = null for datatypes that don't allow null like LONGTEXT and MEDIUMTEXT

Fixes #1722

### CODE REVIEW

**Comment by everyx** [comment]
@dur41d during the #1764, can we close the PR?

**Comment by dur41d** [comment]
@everyx I don't know if #1764 fixes this bug.

**Comment by hemratna** [comment]
@dur41d  I think there is no need for this PR anymore.
Please test with the latest API and let me know.

**Comment by dur41d** [comment]
@hemratna This PR fixes the error where the alter statement contains length parameter for LONGTEXT and MEDIUMTEXT fields. I don't think your PR fixes that.

**Comment by hemratna** [comment]
@dur41d I tested with WYSIWYG interface and change it's MySQL datatype from 
1. `text` to `longtext`
2. `longtext` to `mediumtext`
3. `mediumtext` to `text` 
and it's working fine without this PR.
Please check with the latest API and check at your side and if working fine, Kindly close this PR.

**Comment by rijkvanzanten** [comment]
This effectively ignores the `length` field when using any of the text / blob types, regardless of what the user provided. That's a pretty useful safety net regardless of what issue it fixes

**Pull request merged**
