### PR TITLE
Redesigned star numeric input

### LINKED ISSUE #1371: Nested Filtering (eg: by Status)
# Feature Request

Filter nested fields when retrieving from the API.

Assume a collection author and a collection books nested like:

```
[
   {
      "id":1,
      "name":"Author 1",
      "status":"published",
      "books":[
         {
            "id":1,
            "title":"Book 1",
            "status":"published"
         },
         {
            "id":2,
            "title":"Book 2",
            "status":"draft"
         }
      ]
   },
   {
      "id":2,
      "name":"Author 2",
      "status":"published",
      "books":[
         {
            "id":3,
            "title":"Book 3",
            "status":"draft"
         },
         {
            "id":4,
            "title":"Book 4",
            "status":"draft"
         }
      ]
   }
]
```

In order to view a list of all (published) authors and their respective **published** books I would try a query like:

items/author/status=published&filter[books.status]=published

## What problem does this feature solve?

The above query returns a list of all published authors which **have** published book which is in the case above:

```
[
   {
      "id":1,
      "name":"Author 1",
      "status":"published",
      "books":[
         {
            "id":1,
            "title":"Book 1",
            "status":"published"
         },
         {
            "id":2,
            "title":"Book 2",
            "status":"draft"
         }
      ]
   }
]
``` 

with the requirements above I'd rather expect the following result: 

```
[
   {
      "id":1,
      "name":"Author 1",
      "status":"published",
      "books":[
         {
            "id":1,
            "title":"Book 1",
            "status":"published"
         }
      ]
   }
]
``` 

## How do you think this should be implemented?

Regarding the API I propose a syntax like:

field.filter[nestedField(s)]=value

in my case resulting in 

books.filter[status]=published

## Would you be willing to work on this?

if it makes sense I could contribute to this.

### PR DESCRIPTION
**Pull request by samvasko**
Replaces some outdated code with fresh new UI for numeric star control.

Fixes  https://github.com/directus/app/issues/1371

Known issues
 - [x] The value does not get limited to the maximum. (You can set a value to be greater than max and the API will silently convert it to max but the UI does not update)

screen shot 2019-03-03 at 20 21 05

### CODE REVIEW

**Comment by samvasko** [comment]
I've taken a punt on the design. Appreciate any feedback !

**Comment by rijkvanzanten** [comment]
Hey @samvasko! Thanks for another great PR 😄 

That limiting the value problem was a tricky one to solve! I think this PR is ready to go now, everything else is looking great 😄

**Comment by rijkvanzanten** [comment]
Lemme know when you're ready to get this merged @samvasko! It seems like I can't un-draft it nor force merge it 🤷‍♂️

**Comment by samvasko** [comment]
All good! ⛴

**Comment by adamjgrant** [comment]
Wow. That was fast. Thank you!

**Pull request merged**
