### PR TITLE
Graphql

### PR DESCRIPTION
**Pull request by hemratna**
Merge `graphql` branch to `master`.

### CODE REVIEW

**Comment by herrbomm** [comment]
@hemratna What does that mean? Is GraphQL now in the master included? Means if i "git Pull" GraphQL will be part of Directus now? Sorry - im a Git Noob 😬

**Comment by hemratna** [comment]
@herrbomm Yes, GraphQL is not part of Directus API `master` branch. 
Simply `git pull` will pull add the graphql support. :)
Let me know your feedback. :)

**Comment by herrbomm** [comment]
@hemratna - uhm ... guess u got me wrong. What i was asking IF GraphQL is not part of master-branch ;) 
So if i installed the "normal" Directus suite (master). Whats the easiest way to add GraphQL support then?

Regards,
Fab

**Comment by benhaynes** [comment]
I think Hem meant:

> Yes, GraphQL is **now** part of Directus API master branch.

😉

**Comment by hemratna** [comment]
> @hemratna - uhm ... guess u got me wrong. What i was asking IF GraphQL is not part of master-branch ;)

@herrbomm GraphQL is now part of Directus API repo `master` branch. We will add the Graphql to [Directus suites](https://github.com/directus/directus) on the next release.

> So if i installed the "normal" Directus suite (master). Whats the easiest way to add GraphQL support then?

Until the next release of Directus suite, You can take a separate pull of Directus api `master` branch.

**Comment by herrbomm** [comment]
Thanks guys - so i guess it is stable and later upgrade auf master WITH GraphQL should work without hassle, right? ;)

**Pull request merged**
