### PR TITLE
Feat/azure storage adapter

### PR DESCRIPTION
**Pull request by retrocede**
Add an option for azure file storage blobs as your storage provider.

### CODE REVIEW

**Comment by retrocede** [comment]
Is there anything I can do on this? I'm happy to approach the implementation a different way, and/or to fix the merge conflicts that have crept in over the past six months.

It would be very helpful to not need to manually go in and make these changes on every install though.

**Comment by rijkvanzanten** [comment]
@retrocede That would be amazing. The changes itself look good to me, so if you could update the pr I'll merge it in right away. 

I'm a bit heads down on getting an alpha out for the next major version, but I'm planning to do a little sprint on v8 next week (review/merge prs, release the next minor version)

**Comment by retrocede** [comment]
Sounds great! I created a new pull request, with the changes re-applied over master. I hope that's ok!

**Comment by rijkvanzanten** [comment]
Thanks! That's perfect 🙂 

Closed in favor of #1892

**Pull request closed without merging**
