### PR TITLE
button-group interface

### PR DESCRIPTION
**Pull request by theharshin**
Added a Button-Group Interface.
Need to work on:
- Read-Only module.
- The grouping inside button-groups.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hey @theharshin! We've removed `package-lock.json` from git in the meantime. Could you maybe delete it from this PR so it doesn't get re-added? Thanks! 😄

**Comment by rijkvanzanten** [comment]
For some reason, the styling is different on my end than the screenshot you send over Slack 🤔 

image

(Chrome Version 67.0.3396.99 (Official Build) (64-bit), MacOS)

As soon as the `readonly.vue` component is done and that styling issue is fixed, this will be merged in 😄

**Comment by benhaynes** [comment]
Hey @rijkvanzanten – I spoke with @theharshin on Slack, he's going to add grouping (he said he spoke to you about the JSON format) and a "flat" style and then we should be good!

**Comment by theharshin** [comment]
Added Grouping & Theme support.
`readonly.vue` component added.

image

**Comment by rijkvanzanten** [comment]
Amazing job @theharshin! 😄 I love the fact how you used the button group interface for an option of the button group interface :)

**Comment by rijkvanzanten** [comment]
Oh we do have 1 problem! It doesn't show the value that has been saved to the DB on load.

**Comment by rijkvanzanten** [comment]
Easy fix luckily 🙂

**Comment by benhaynes** [comment]
This is amazing @theharshin – thank you again for all the hard work!!

**Comment by theharshin** [comment]
Thanks, @benhaynes & @rijkvanzanten. Loved working on this component & Directus. Learned so many things 😇

**Pull request merged**
