### PR TITLE
Fix issue when deleting a file and saving the item

### PR DESCRIPTION
**Pull request by JbalTero**
Fix issue when deleting a file and saving the item. [Screencast of the issue fixed](https://drive.google.com/file/d/1J-vMIfooLJDN70AaMw57F84U-QH2vA6J/view?usp=sharing)

### CODE REVIEW

**Comment by bjgajjar** [comment]
Hey Jim,

Thanks for your time to send the PR. But I need some more info for this as I am not able to replicate it in neither Dev server (Master branch) nor Local env (Dev-Branch).

Can you please verify from the below recording whether am I missing any steps or not?

ezgif com-video-to-gif

**Comment by JbalTero** [comment]
@bjgajjar Your steps were correct. Try this dump

https://drive.google.com/file/d/1abN8HupkJzzCRs3nTBgSNLJQY7pbxt5_/view?usp=sharing

admin@test.com
pg025Y4GWKf8OyaSm8iM

**Comment by JbalTero** [comment]
@bjgajjar What PHP version is directus demo using?

**Comment by bjgajjar** [comment]
> Try this dump

Checking it and let you know soon.

> What PHP version is directus demo using?

I am not aware of that. Ben/Rijk is the right person to answer this.
But I can tell you about my local - It's 7.3.8

**Comment by bjgajjar** [comment]
Hey Jim,
Yes, it's replicated in the Develop branch. I was in the master branch at local. That's why I didn't replicate it earlier. 

This PR will resolve it :)

**Pull request merged**
