### PR TITLE
Calendar Layout

### PR DESCRIPTION
**Pull request by Nitwel**
Yay 😄

### CODE REVIEW

**Comment by Nitwel** [comment]
directus/app#1191

**Comment by benhaynes** [comment]
@Nitwel — for "color support", does this allow you to choose one global color for events in the layout, or map to a `color` field in the collection? The latter would be really nice since then you could have different colored events based on type.

**Comment by Nitwel** [comment]
I did it that every event could have their own color. If this is not enabled or the color isnt set, I use the --accent color for it

**Comment by Nitwel** [comment]
@benhaynes you can ckeck it out again, if you want (using Directus X.0.10 ^^)

**Comment by rijkvanzanten** [comment]
image

I think we have a little bit of a situation here 😵

**Comment by Nitwel** [comment]
How did you changed the Timezone, so I can test it too?

**Comment by rijkvanzanten** [comment]
Left is Chrome, right is Safari. I didn't change anything else 🤔

**Comment by benhaynes** [comment]
Sooooo nice!! A few little tweaks:

* I am seeing the emoticon even when there are events there (see below)
* I see you added a mouse scroll for months, but on my Mac mouse that is going crazy fast ⚡️ ... no matter how hard I try it scrolls through 10+ months.
* Can we "re-process" the `and 2 more...` when the page resizes? When I shrink/expand my screen it doesn't update

screen shot 2019-01-14 at 5 34 53 pm

**Comment by rijkvanzanten** [comment]
Also, I don't know if this is even possible in the way we render the fields (haven't swam through the code enough), but maybe we can render the months side by side using [`scroll-snap`](https://css-tricks.com/practical-css-scroll-snapping/)? That way we don't have to use javascript scroll handlers and avoid any scroll issues

**Comment by Nitwel** [comment]
I guess it has to do with Safari, that it is a bit conceited in the way it wants things to work and how others think it should work. 😃

**Comment by rijkvanzanten** [comment]
https://twitter.com/keeskluskens/status/1084814388882739202

**Comment by Nitwel** [comment]
> I see you added a mouse scroll for months, but on my Mac mouse that is going crazy fast ⚡️ ... no matter how hard soft I try it scrolls through 10+ months.

Improved

> I am seeing the emoticon even when there are events there (see below)

Should be fixed when the dates are also fixed

> Can we "re-process" the and 2 more... when the page resizes? When I shrink/expand my screen it doesn't update

Just need to figure out how to update this

> Also, I don't know if this is even possible in the way we render the fields (haven't swam through the code enough), but maybe we can render the months side by side using scroll-snap? That way we don't have to use javascript scroll handlers and avoid any scroll issues

The scrolling @benhaynes mentioned is used just as a shortcut
The accual "scrolling" to the side is a Vue Transition

I HOPE that I finaly fixed the days issue -.-

**Comment by rijkvanzanten** [comment]
This is all looking good now on my end @Nitwel 😄

**Comment by Nitwel** [comment]
Finally its fixed.😅
The pain has come to a hold.😥

**Comment by benhaynes** [comment]
Hey @Nitwel — it looks like the "Date" option doesn't accept the `datetime` type. Is there any way to allow for that type?

**Comment by Nitwel** [comment]
That would be possible to add but would need a little more programming.

**Pull request merged**
