### PR TITLE
Wysiwyg replacement

### PR DESCRIPTION
**Pull request by dev7ch**
Replacing Quill with https://tiptap.scrumpy.io/

https://github.com/directus/app/issues/1234

Please write down in the comment here which features are missing/need/desired

*features* 

- [x] edit wysiwyg input as raw html
- [x] insert images from any url
- [x] HTML table buidler
- [x] insert images from directus upload and select extension widget
- [x] Add hyperlink with moving bubble on selection 
- [x] allow editor extensions to be configurable in Admin UI
- [x] include redo and undo options
- [x] include forrmatted raw html (codeMirror) optionally
- [x] make editor plugins sortable from admin UI

**todos before realese**
- [ ] finish `meta.json` updates
- [ ] scss styles scoped
- [ ] update Readme and exentsion docs
- [ ] pasting or insert an image doest emit input changed to directus (you cant save without keypress currently)

**todos after release**

- [ ] translations
- [ ] uploading image 
- [ ] allow defining HTML templates in Admin UI
- [ ] allow setting an image default source

*Bugs*

~~if you save in raw html mode after edit the field content is deleted on save~~

### CODE REVIEW

**Comment by benhaynes** [comment]
Awesome! Thanks @dev7ch — we'll take a look at this Friday and send any feedback! 😄

**Comment by dbrw** [comment]
can we edit the html code directly with this setup?

**Comment by dev7ch** [comment]
currently, there seems not to be a "View Source" option included by this editor out of the box.

**Comment by dev7ch** [comment]
update: https://github.com/scrumpy/tiptap/issues/58

**Comment by dev7ch** [comment]
@benhaynes @rijkvanzanten what do you think about the current state?

- Ready to merge or what else is needed for version 1.0.0 ?
- is there a Readme template for plugins?

**Comment by benhaynes** [comment]
Hey @dev7ch — we'll review this today and let you know!

🔔 @rijkvanzanten

**Comment by dev7ch** [comment]
Hey @benhaynes great!  I am still in the desert. I ll be back in 3 days.

This PR is outdated... Plz review this PR https://github.com/directus/app/pull/1441

**Comment by benhaynes** [comment]
Haha, I saw your last comment on March 22 and thought it was from today (April 22)... too early!

Enjoy the 🏜!

**Pull request closed without merging**
