### PR TITLE
Fix #1502 [Required doesn't work with O2M type]

### LINKED ISSUE #1502: Required doesn't work with O2M type
If you use `O2M Files interface` you cannot update the item. You should deselect files and reselect them.

[Link to the video - since the gif becomes 170MB](https://drive.google.com/file/d/1s3Bv-7ruGB2IK3VRqv_ANGtf385Lt04W/view?usp=sharing)

Screen Shot 2019-11-27 at 16 16 17

### PR DESCRIPTION
**Pull request by bjgajjar**
Fixes #1502

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@bjgajjar Can you take a look at the merge conflicts? I don't want to screw anything up 🙂

**Comment by rijkvanzanten** [comment]
I'm getting a 500 on creating a new item:

```
[2020-01-07 10:48:38] api[thumper].ERROR: Error: Call to undefined method Directus\Database\Schema\Object\FieldRelationship::getJunctionOtherRelatedField() in /var/www/html/src/core/Directus/Services/ItemsService.php:206
```

**Comment by bjgajjar** [comment]
@rijkvanzanten - Apologise. That was a mistake on resolving the conflict which is resolved. You can check it :)

**Comment by rijkvanzanten** [comment]
The PR doesn't seem to work on my end.. I'm still getting

```
message: "Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Null' at line 1)"
```

**Pull request merged**
