### PR TITLE
Add CLI cache:clear

### PR DESCRIPTION
**Pull request by JbalTero**

### CODE REVIEW

**Comment by JbalTero** [comment]
Just found [this](https://github.com/directus/api/issues/507#issuecomment-450432962)

Why is the cache module removed? being able to clear cache on the fly is important.

**Comment by benhaynes** [comment]
Hmm, not sure. It seems that the code was written for Directus 6 (a completely different codebase) so maybe it wasn't working/applicable any more?

**Comment by shealavington** [comment]
I would agree Ben, the post does mention

>it was an under development module made for Directus 6.

**Comment by bjgajjar** [comment]
Hey @benhaynes 

Checked this code. And it is working as expected. After executing `cache:clear` in CMD it is removing all the cache. So there's no harm to merge. Let me know what are the further steps we should do for this PR :)

**Comment by benhaynes** [comment]
Sounds good to me! Thanks Binal...

**Comment by rijkvanzanten** [comment]
I don't think there's any additional steps needed for this right? LGTM!

**Pull request merged**
