### PR TITLE
New Feature - Pagination - Initial Commit: Awaiting Feedback!

### PR DESCRIPTION
**Pull request by philleepflorence**
Added pagination and filter_count - will update docs once approved.

### CODE REVIEW

**Comment by philleepflorence** [comment]
"Fixes: #673".
"Fixes: #340".

**Comment by benhaynes** [comment]
Thanks @philleepflorence!! We've been swamped this week, but will check this out Monday!

**Comment by bjgajjar** [comment]
@philleepflorence 

Thanks for the PR. But you should work on the `page` parameter instead of `limit` and `offset`. As if we are adding the feature of `pagination` feature then it should rely on the `page` parameter. Your current code develop with `limit` and `offset` which is returning  the object like 

```
{
  "paging": {
    "limit": 10,
    "page": 2,
    "pages": 87,
    "previous": {
      "offset": 0,
      "link": "http://example.com/_/items/projects?meta=total_count,result_count,status,paging&limit=10&offset=0"
    },
    "next": {
      "offset": 20,
      "link": "http://example.com/_/items/projects?meta=total_count,result_count,status,paging&limit=10&offset=20"
    }
  }
}
```

We need `page` instead of `limit` and `offset` here.

Please go through the below link for more details of the pagination. You can get the sample object from the #340 

http://jsonapi.org/format/#document-links
http://jsonapi.org/format/#fetching-pagination

**Comment by philleepflorence** [comment]
I am not sure I understand the request. 
If we do not have a `limit` parameter but a `page` parameter, there would be an extra overhead as there would be a request to the database to parse the `page` parameter, as of now, there is no pre-processing as the `limit` and `offset` are built into the Directus Core, only if a user passes a `pagination` parameter do we send back pagination metadata.
I have no problem sending back the metadata structured in any format you want, but I am hesitant to change too much of the logic within Directus.
Please Advise.

**Comment by rijkvanzanten** [comment]
@philleepflorence Could you provide an example of how this would look IRL input / output wise? @bjgajjar a `page` parameter would/should be nothing more than `page-number * offset`

**Comment by philleepflorence** [comment]
@rijkvanzanten - sure, see below for sample input and output...
INPUT: `http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&q=Arrow&limit=20&offset=20&pagination=1`
OUTPUT:
```
{
    "meta": {
        "collection": "app_icons",
        "type": "collection",
        "result_count": 20,
        "total_count": 3040,
        "filter_count": 103,
        "paging": {
            "limit": 20,
            "page": 2,
            "pages": 6,
            "previous": {
                "offset": 0,
                "link": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&q=Arrow&limit=20&offset=0&pagination=1"
            },
            "next": {
                "offset": 40,
                "link": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&q=Arrow&limit=20&offset=40&pagination=1"
            }
        }
    },
    "data": []
}
```

**Comment by rijkvanzanten** [comment]
What does the pagination parameter do @philleepflorence?

**Comment by philleepflorence** [comment]
Sorry, removed it, that was an old thought, the page parameter would be inside the meta parameter - @rijkvanzanten

**Comment by benhaynes** [comment]
This looks good to me @philleepflorence.

@bjgajjar — do you have concerns with this metadata approach?

**Comment by bjgajjar** [comment]
@benhaynes @rijkvanzanten 

I am aware of the logic of the `page` parameter. But as I mentioned above; when the `page` parameter passes in API then there is no need to pass the `limit` and `offset`. We are developing this functionality as the user can access the pagination using 2 ways.

- With passing `limit` and `offset` parameter
- With passing the `page` parameter

@philleepflorence 

You don't need to make a major change for this functionality. When API have `page` parameter then just need to calculate `offset` using `page` and `limit` and then pass those values to the Directus Core function.

You can get the `offset` using below logic

`offset = (page-1) * limit;`

Here you can accept the `limit` parameter from API. So the user can customize the value of item per page. If API doesn't have the `limit` parameter then the default value will be considered.

**Comment by philleepflorence** [comment]
I was hesitant to the page parameter because on some of my applications you can change the limit (number of items in the feed) on the fly which affects the page number so the two absolutes were always limit and offset coming into the API so the API is agnostic of the page number until it calculates the page based on the limit and offset. 

But I am open to what you need.

Please advise.

**Comment by philleepflorence** [comment]
I was trying to keep to the current architecture without making too big a change to the documentation and codebase.

**Comment by bjgajjar** [comment]
@philleepflorence 

Agree with you! 

But as I mentioned we can pass the `limit` from API to customize the item per page. So It will not affect the page number. 

And as per your current code, API doesn't have any `page` parameter as input but getting that in the output. So I would suggest accepting the `page` parameter which is suggested by Wellingguzman in #340.

You don't need to make major changes you just need to calculate `offset` based on `page` and `limit` (Either get from the input if exist Or take the default value) and then just pass it to the Core function.

Here there will be one more scenario; where the user may pass `limit` and `offset` along with `page` parameter. So please make sure to give the priority to `limit` and `offset` instead of `page`.

Let me know your thoughts @benhaynes

**Comment by benhaynes** [comment]
I believe I'm following along... here are my questions:

If you provide a `limit` and `page` does that allow you to dynamically change the items per page in that call?

Also, some thoughts on key naming...
* `paging` could be `pagination` (as the grouping for all of this)
* `page` could be `current_page` or `page_current`, but maybe page makes sense so it matches the query string?
* `pages` should be `page_count`
* `previous` could be `prev` (thoughts?)
* Do we want to add `first` and `last`?
* For the query string, it seems like `&pagination=1` should be `&page=1` (right?)

**Comment by bjgajjar** [comment]
Hey @benhaynes, 

> If you provide a `limit` and `page` does that allow you to dynamically change the items per page in that call?

Yes, as items per page is nothing else but the `limit`.  If the user passes `limit` as an input along with `page` parameter, then it will be considered from there otherwise the default value of `limit` will be considered.

I agree with your suggestions for the `key` naming.

> * Do we want to add `first` and `last`?

Yes, we need to add `first` and `last` because if someone wants to add first and last in their pagination link then it will be useful for them.

**Comment by philleepflorence** [comment]
> If you provide a limit and page does that allow you to dynamically change the items per page in that call?

The `offset` (page * limit) can be calculated if the `limit` and `page` parameters are passed through without having to do a 3rd query to the DB. That was what I was trying to avoid earlier since now we perform 2 queries to the DB to get items and then `filter_count` and `pagination`.

> Also, some thoughts on key naming...

If you could let me know what the final object should look like, I can make that update and push back online over the weekend, since it seems we are in agreement over implementation. I know we have the JSON standard, but we need to keep the nomenclature in line with Directus.

Thoughts @rijkvanzanten?

**Comment by rijkvanzanten** [comment]
How about instead of 1 nested `paging` object we add several:

`limit`, `current_page`, `total_pages`, `links`

```json
"limit": 40,
"current_page": 5,
"total_pages": 20,
"links": {
    "self": "https://demo-api.directus.app/_/items/articles",
    "next": "https://demo-api.directus.app/_/items/articles?offset=40&limit=40",
    "last": "https://demo-api.directus.app/_/items/articles?offset=120&limit=40"
}
```

**Comment by philleepflorence** [comment]
Okay cool, and for the number of rows returned when filtering - `filter_count`?

**Comment by rijkvanzanten** [comment]
That works, but... it also kinda sounds like the amount of filters that were applied. Maybe `filtered_count`?

**Comment by benhaynes** [comment]
Rijk and I just discussed this and he's updated his response above. The formatting/keys he has there are good to go!

**Comment by philleepflorence** [comment]
So go with the following?
```
"limit": 40,
"page": 5,
"page_count": 20,
"filtered_count": 100,
"links": {
    "self": "https://demo-api.directus.app/_/items/articles",
    "next": "https://demo-api.directus.app/_/items/articles?offset=40&limit=40",
    "last": "https://demo-api.directus.app/_/items/articles?offset=120&limit=40"
}
```

**Comment by rijkvanzanten** [comment]
Yes 💪

**Comment by philleepflorence** [comment]
Cool!

**Comment by rijkvanzanten** [comment]
Any updates on this? Eagerly awaiting this functionality in the API 🙂

**Comment by philleepflorence** [comment]
I will release this Saturday or before.
Sorry for the delay.

**Comment by philleepflorence** [comment]
@benhaynes and @rijkvanzanten : Since the `filtered_count` is now very important, should it be included in all filtered results response even if pagination is not?
Or should I just activate pagination in all responses since it is the same DB query that gets the `filtered_count` that also processes the `pagination`?
Updated the code to the new schema, will push once you confirm...

**Comment by philleepflorence** [comment]
Current metadata response when the `limit` parameter is not provided, but a `page` parameter is provided:
```
{
    "meta": {
        "collection": "app_icons",
        "type": "collection",
        "result_count": 63,
        "total_count": 3040,
        "filter_count": 63,
        "limit": 1,
        "offset": 2,
        "page": 3,
        "page_count": 63,
        "links": {
            "self": "http://api.directus.local/_/items/app_icons",
            "first": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=1&offset=1",
            "last": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=63&offset=62",
            "next": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=4&offset=3",
            "previous": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=2&offset=1"
        }
    },
    "data": [...]
}
```

**Comment by philleepflorence** [comment]
Metadata response with the `limit` and `page` parameters:
URL: `http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=2&limit=10`

```
{
    "meta": {
        "collection": "app_icons",
        "type": "collection",
        "result_count": 10,
        "total_count": 3040,
        "filter_count": 63,
        "limit": 10,
        "offset": 20,
        "page": 3,
        "page_count": 7,
        "links": {
            "self": "http://api.directus.local/_/items/app_icons",
            "current": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=2&limit=10",
            "first": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=1&limit=10&offset=10",
            "last": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=7&limit=10&offset=60",
            "next": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=4&limit=10&offset=30",
            "previous": "http://api.directus.local/_/items/app_icons?access_token=directus@admin&meta=*&filter[keywords][contains]=account&page=2&limit=10&offset=10"
        }
    },
    "data": [...]
}
```

**Comment by bjgajjar** [comment]
@philleepflorence 

PR seems okay but there's one question which I need to ask you as well as @benhaynes  and @rijkvanzanten. Right now for the first page the `previous` link set with the `page` value "-1" and for the `last` page the `next` link is set with the `page` value "1". But I think we need to set the `page` as null here so if user want to make the `Next` and `Previous` button disable then they can do that easily.

Let me know your thoughts!

**Comment by benhaynes** [comment]
In the example @rijkvanzanten made above, he excluded the first/previous when on page one. I'm fine with setting these to whatever, but the values should be consistent.

**Comment by bjgajjar** [comment]
@benhaynes  Agreed! We have to exclude those values or need to set those as `null`. If @rijkvanzanten 
also agreed on that then @philleepflorence please apply the needful changes on PR :)

**Comment by shealavington** [comment]
I would agree on null, otherwise, I believe you could end up with `Cannot read 'last' of undefined`. :roll_eyes: :joy:

**Comment by rijkvanzanten** [comment]
> Since the filtered_count is now very important, should it be included in all filtered results response even if pagination is not?

`filtered_count` should be a separate `meta` value, that's separate from pagination.

**Comment by philleepflorence** [comment]
I will update and push back online tomorrow...

**Comment by philleepflorence** [comment]
Assumptions:

- `Limit` always takes precedence over the `page` parameter - so if the `result_count` is 10 and `limit` is 10, but `page` is 2, the `page` parameter would be corrected to 1.
- If there is only one page, (`page_count` = 1), `first`, `last`, `next`, and `prev` would be `null`.

**Comment by rijkvanzanten** [comment]
Can we also make sure that

* `prev` is `null` when `page = 1`
* `next` is `null` when `page = pages.length`

**Comment by philleepflorence** [comment]
Confirmed - will update later tonight if applicable.

**Comment by philleepflorence** [comment]
CONFIRMED:

If you are on page 1 of 12, then `prev` should be `NULL` as you can't go to `0`
If you are on page 12 of 12, then `next` should be `NULL` as you can't go to `13`
If you are on page 1 of 1, then `next`, `prev`, `first` and `last` should be `NULL` as you can't go to `0` or `2`

**Pull request merged**
