### PR TITLE
Fix issue while update item.

### PR DESCRIPTION
**Pull request by hemratna**

### CODE REVIEW

**Comment by JbalTero** [comment]
@hemratna the updating of item is fixed, now the deleting of item has the same error.

**Comment by JbalTero** [comment]
@hemratna to replicate the delete issue: do [this](https://drive.google.com/file/d/1a9pUGmwJ954Mz6knJDbi2KF1Wa11OoX1/view?usp=sharing)

The issue is: Deletion on collection with one-to-many relationship and the delete mode is delete relationship.

**Comment by JbalTero** [comment]
@hemratna created the issue here: https://github.com/directus/api/issues/1229

**Comment by hemratna** [comment]
#1229 is not due to this PR, It's an already in `develop` branch. So let's track the delete issue separately on #1229.

**Comment by JbalTero** [comment]
Thanks

**Pull request merged**
