### PR TITLE
Removing relationship metadata (directus_relations)

### PR DESCRIPTION
**Pull request by daniel-upzzle**
In the dropColumn method of TableService I added a call to a new method on the same service called "removeRelationship" in case the column has any relationship.

The new method is in charge to remove data related to the relationship of the field being removed.

### CODE REVIEW

**Comment by daniel-upzzle** [comment]
It's lack was causing some troubles when adding, removing, readding relations to collections.

**Comment by benhaynes** [comment]
Thanks @daniel-upzzle !!

Could you remind me which issue this resolves? Is it https://github.com/directus/app/issues/1045?

**Comment by daniel-upzzle** [comment]
I think this will resolve the issue you mention. But I've done this because I've found a similar issue.

1) create a many to many relationship or many to one
2) remove the field with that relation (also using the app)
3) create the field again with a new type of relation (or the same in some cases).
4) couldn't reedit the field options nor include items in a relation

I've found that removing manually the implied directus_realtions I could create the fields again without issues.

**Comment by daniel-upzzle** [comment]
I don't know if I have to close this pull request.

**Comment by benhaynes** [comment]
Hey @daniel-upzzle – why was this closed?

**Comment by daniel-upzzle** [comment]
Sorry, I'm new using pull requests, forking etc. I wasn't able to create a new PR aside from this one, because it was in my master branch.

One thing I don't understand is why fetching from the upstream (and rebasing its master to my master) did not eliminate the changes of this PR I have locally when the upstream remote branch being fetch has not this changes applied yet.

**Comment by rijkvanzanten** [comment]
Hey @daniel-upzzle! Is that first commit https://github.com/directus/api/pull/537/commits/b14a933299613c20269e4cd2a2cdf9d931e4d728 the only one you'd like merged? I can clean up the history of this PR a bit but I don't want to delete any other changes you've made 🙂

**Comment by daniel-upzzle** [comment]
Richt @rijkvanzanten , that is the commit making the point.

Thanks!

**Pull request closed without merging**
