### PR TITLE
Fix #1561 [Password reset token won't invalidate]

### LINKED ISSUE #1561: Pw reset token won't invalidate
# Bug Report

Pw reset token can be used to change pw multiple times without expiring.

## Steps to Reproduce

1. Go to admin login
2. Click on 'Forgot password'
3. Click pw reset url of the email received
4. Enter new password and submit
5. Reload page
6. Enter another password and submit

## Expected Behavior

Error message saying pw reset token is expired

## Actual Behavior

Pw gets changed again

## Other Context & Screenshots

There's a TODO comment in line 478 of api/src/core/Directus/Authentication/Provider.php – so it's not implemented correctly yet?

## Technical Details

- Device: Desktop, iPhone 8
- OS: MacOs 10.15.2, iOS 13.2
- Web Server: Apache
- PHP Version: 7.3
- Database: MySQL 8.x
- Install Method: cloned `master` branch

### PR DESCRIPTION
**Pull request by bjgajjar**
Fixes #1561

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Why did you end up going with the password last updated at column? What where your considerations compared to the password-reset-token column?

**Comment by rijkvanzanten** [comment]
Also, when going with a last reset at column, we should make sure that it also gets filled when changing your password normally

**Comment by bjgajjar** [comment]
>Why did you end up going with the password last updated at column? What where your considerations compared to the password-reset-token column?
Also, when going with a last reset at column, we should make sure that it also gets filled when changing your password normally

Thank you so much for indicating these points and I'm really sorry for overlooked these points.

**Comment by rijkvanzanten** [comment]
No worries, just making sure we don't rush into something 🙂

**Comment by rijkvanzanten** [comment]
@bjgajjar This PR ready to go? 🙂

**Comment by bjgajjar** [comment]
@rijkvanzanten  - Yes :)

**Pull request merged**
