### PR TITLE
Make the use if the telemetry service configurable

### PR DESCRIPTION
**Pull request by arboehme**
The new config option for the API to enable / disable the using of telemetry service  (see https://github.com/directus/docs/issues/167)

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
The config file for the application has been removed in v8. I've implemented the same functionality in 4ccfb981.

**Comment by rijkvanzanten** [comment]
My bad! Mistakenly closed the API one instead of the app one.

**Comment by bjgajjar** [comment]
@arboehme - Thanks for the PR. But we should use the `telemetry` flag from the DB instead of the `config` file. You can find that flag from the `directus_settings` table. 

It'll be great help if you can update this PR based on DB instead of configuration. :)

**Comment by arboehme** [comment]
> It'll be great help if you can update this PR based on DB instead of configuration. :)

@bjgajjar Sorry, I have not so much time in last time.... but, I see you already changed my implementation accordingly. Thank you very much!

**Pull request merged**
