### PR TITLE
Allow to set metadata for files on creation

### PR DESCRIPTION
**Pull request by dev7ch**
Attention, this it not tested, i hope this will work, due currently it looks like its not allowed to set metadata on creation, which would be nice

### CODE REVIEW

**Comment by dev7ch** [comment]
Dear @bjgajjar do you see any obstacles on this?

**Comment by dev7ch** [comment]
thanks 😊

**Comment by inta** [comment]
`'metadata' => isset($file['metadata']) ? $file['metadata'] : null,`
Shouldn't that be called `$fileData` instead of `$file`?
Adding metadata is currently broken, but I don't know if this is the cause.

**Comment by dev7ch** [comment]
mmh yes, could be .. i have not tested it

**Comment by ThaDaVos** [comment]
This does definitely break metadata - also, this was not needed as one could already set `metadata` on file creation (we were doing this already)

@rijkvanzanten - can this PR be reverted and a `8.8.2` released?

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten - can this PR be reverted and a 8.8.2 released?

I'm afraid not. v8 has been end-of-life since November 2020, and won't receive any new updates from the core team.

**Pull request merged**
