### PR TITLE
Fix 1759 [Changing signed state doesn't work]

### LINKED ISSUE #1759: Changing signed state doesn't work
Sending `{ signed: false }` in a PATCH to /fields doesn't set the signed state to false for a numeric value and returns `{ signed: true }`.

### PR DESCRIPTION
**Pull request by hemratna**
fixes #1759

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
How does this fix it? Have you tested this implementation? If so, how did you test it? 

This feels like a insecure solution, as this doesn't check for datatype of the column before attempting to set `signed`, or am I mistaken?

**Comment by hemratna** [comment]
@rijkvanzanten  I want to mention one thing here. 
The following issues are related to #1601 
  #1765 
  #1759 
  #1749 
  #1739 
  #1756

So I am removing the #1601 code and trying to solve that PR related issue #1463. So after that all above mentioned issues will be solved.

**Comment by hemratna** [comment]
After this commit It will solve all above mentioned issues

**Comment by hemratna** [comment]
The PR #1601 for issue #1463 runs an `ALTER` query when the user modifies any column. 
The code for the `ALTER` query doesn't consider the current status of `autoincrement`, `unsigned`, `default`, etc. and alter for `required`.

In this PR I am removing the code of the PR #1601 and fix the issue #1463 by setting `$column->setNullable($nullable);` based on user input.

So by reverting PR #1601 all the above mentation issues will be fixed.

----------------------
Regarding the testing,

I created a collection with 
one textbox, set `required=false` as well as `required=true` (To test #1443)
one numeric field, set `required=false`, `required=true`, `signed=true`, `signed=false` (To test #1759 )

I also try to reproduce the below-listed issue after fixing this code in my local.

#1765
#1759
#1749
#1739
#1756
#1668 
#1691 

---------------------------

> This feels like a insecure solution, as this doesn't check for datatype of the column before attempting to set signed, or am I mistaken?

The code for the `signed` is already in place with default value @ https://github.com/directus/api/blob/master/src/core/Directus/Database/Schema/SchemaFactory.php#L216

But the PR #1601 override these values.

**Pull request merged**
